### ISSUE TITLE
In mergejob_utils.py file; In the env {} dataset_format is not mentioned):

### ISSUE THREAD

**Issue by kitasid** [brunopistone/sm-end-to-end-mlops#1]
@brunopistone In sm-end-to-end-mlops/seed_code/01-ml-deploy/utils/mergejob_utils.py, On calling the _run_merge_job_processor_ function. I'm getting the below errors

![p122](https://user-images.githubusercontent.com/74685231/191014665-b909ce1d-d1b3-4211-91a6-e06d5871fa5a.PNG)
![p123](https://user-images.githubusercontent.com/74685231/191014676-0598ac9b-ddbb-4681-8725-b81df8b0df54.PNG)

Q1. What should be passed in dataset_format?
Q2. Is it important to pass kms_key as a parameter?

**Comment by brunopistone** [comment]
Hello @itsmesid12. regarding the first error, it seems that it's not able to merge the test data with the ground truth data., so you should check your input dataset.

For the second question, kms it's not mandatory. If it's not configured in your environment you can avoid it in your jobs
